# Generated by Django 5.2 on 2025-04-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiotechBin', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expirationdate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='expirationdate',
            name='strike_price',
        ),
        migrations.AlterUniqueTogether(
            name='strikeprice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='strikeprice',
            name='ticker',
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField()),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('option_type', models.CharField(choices=[('CALL', 'Call'), ('PUT', 'Put')], max_length=4)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='BiotechBin.ticker')),
            ],
            options={
                'db_table': 'options',
            },
        ),
        migrations.CreateModel(
            name='OptionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_collected', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.IntegerField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='BiotechBin.option')),
            ],
            options={
                'db_table': 'option_prices',
            },
        ),
        migrations.DeleteModel(
            name='DatePrice',
        ),
        migrations.DeleteModel(
            name='ExpirationDate',
        ),
        migrations.DeleteModel(
            name='StrikePrice',
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['ticker', 'expiration_date', 'strike_price', 'option_type'], name='options_ticker__2219ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('ticker', 'expiration_date', 'strike_price', 'option_type')},
        ),
        migrations.AddIndex(
            model_name='optionprice',
            index=models.Index(fields=['option', 'date_collected'], name='option_pric_option__8bc3e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='optionprice',
            unique_together={('option', 'date_collected')},
        ),
    ]
